spring.application.name=customer-service
info.app.version=1.0.0
info.app.description=Customer Service

server.port=8100

log.format=text

web.component.scan=com.deviceshop.customer

cloud.connector=none

snake.case.serialization=true

show.application.properties=server.port, spring.application.name, cloud.connector
